export const AUTH_SUCCESS = "auth_success"; // 登录/注册成功
export const ERROR_MSG = "error_msg"; //错误提示信息
export const RECEIVE_USER = "receive_user"; //接收用户
export const RESET_USER = "reset_user"; //重置用户
export const RECEIVE_WHEATHER = "receive_wheather"; //获取天气
export const RECEIVE_CATEGORYS = "receive_categorys"; //接收分类列表
export const ADDCATEGORY_SUCCESS = 'addcategory_success'  //添加商品成功
export const UPDATECATEGORY_SUCCESS = 'updatecategory_success'  //更新商品成功
export const RECEIVE_PRODUCTS = 'receive_products'  //接收商品列表
export const ADDPRODUCT_SUCCESS = 'addproduct_success' //添加商品成功
export const UPDATEPRODUCT_SUCCESS = 'updateproduct_success' //更新商品成功
export const RECEIVE_ROLE_LIST = 'receive_role_list'  //接收角色列表
export const RECEIVE_USER_LIST = 'receive_user_list'  //接收用户列表
